environment:
  sdk: ">=3.0.0 <4.0.0"name: smart_farm
description: A Flutter authentication demo app with login, signup and forgot password

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # LOCAL STORAGE (for remember login, saved user, password reset)
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true